export const GET_STUDENTS="GET_STUDENTS"
export const STUDENTS_ERROR="STUDENTS_ERROR"

export const ADD_STUDENT="ADD_STUDENT"
export const ADD_STUDENT_SUCCESS="ADD_STUDENT_SUCCESS"
export const ADD_STUDENT_ERROR="ADD_STUDENT_ERROR"

export const EDIT_STUDENT="EDIT_STUDENT"
export const EDIT_STUDENT_SUCCESS="EDIT_STUDENT_SUCCESS"
export const EDIT_STUDENT_ERROR="EDIT_STUDENT_ERROR"

export const GET_STUDENT_EDIT="GET_STUDENT_EDIT"
export const GET_STUDENT_EDIT_SUCCESS="GET_STUDENT_EDIT_SUCCESS"
export const GET_STUDENT_EDIT_ERROR="GET_STUDENT_EDIT_ERROR"

export const DELETE_STUDENT="DELETE_STUDENT"

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const EDIT_NOTIFICATION='EDIT_NOTIFICATION';
export const DELETE_NOTIFICATION='DELETE_NOTIFICATION'

export const TR_TRANSLATE='TR_TRANSLATE'